name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and release image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.26.2
          args: release --clean --verbose
